import React, { useState, useEffect } from "react";
import { Wallet } from "../utils/nearconfig";
import Head from "next/head";


export default function SignOut() {
    const [connected, setConnected] = useState(false);
    const [failedConnect, setFailedConnect] = useState(false);

    useEffect(() => {

        Wallet().then(async (tx) => {
            if (tx.isSignedIn()) {
                tx.signOut();
            }

            setConnected(true);
        }).catch((e) => {
            console.log(e.message)
            setFailedConnect(true);
        });
    }, [])


    

    return (
        <div id="app-path">
            <Head>
                <title>NEAR Wallet Connection</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div id="header">
                <p>Connect Wallet</p>
            </div>

            <div id="info-section">
                <div id= "fail-connect">
                {connected ? <>
                    <h1>
                        Successfully signed out from NEAR Wallet
                    </h1>

                    <button onClick= {() => alert('done')}>
                        OK
                    </button></>
                 : <p>Disconnecting NEAR Wallet ...</p>}
                </div>
                
                    

            </div>

            
            


            <div id="footer">
                <div>
                <p>This page is part of Distancia confirmation policy. Read more here</p>
                <p>Copyright. Distancia 2022</p>
                </div>
                
            </div>
            
        </div>
    )
}